services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:4000"
    # Anonymous volumes - Bind mount and sync
    # Sync local codebase with Docker image code
    # volumes:
    #   - .:/app
    #   - /node_modules
    # environment:
    #   - PORT=4000
    env_file:
      - ./.env
  
  mongo-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    # Named volume for persistent storage
    volumes:
      - mongo-db-data:/data/db

volumes:
  mongo-db-data: